In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv("F:/ML_algo/datasets/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

# train test split

In [9]:
X=df.drop(columns=['has_covid'])
y=df['has_covid']

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [14]:
X_train

    age  gender  fever   cough       city
15   70    Male  103.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi
30   15    Male  101.0    Mild      Delhi
79   48  Female  103.0    Mild    Kolkata
86   25    Male  104.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
24   13  Female  100.0  Strong    Kolkata
80   14  Female   99.0    Mild     Mumbai
57   49  Female   99.0  Strong  Bangalore
69   73  Female  103.0    Mild      Delhi
60   24  Female  102.0  Strong  Bangalore

[80 rows x 5 columns]

In [15]:
from sklearn.compose import ColumnTransformer

In [17]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [19]:
transformer.fit_transform(X_train).shape

(80, 7)

In [21]:
transformer.transform(X_test).shape

(20, 7)